language: ruby
sudo: false
bundler_args: --without development system_tests
script:
  - "bundle exec $CHECK"
notifications:
  email: false
rvm:
  - 2.1.9
  - 2.2.0
  - 2.3.0

env:
  - "CHECK='rspec -fd -c spec/unit'"

matrix:
  fast_finish: true
